apiVersion: ec2.aws.gke.cloud.google.com/v1beta1
kind: VPC
metadata:
  name: vpc-staging
  labels:
    env: staging
spec:
  providerConfigRef:
    name: default-aws
  forProvider:
    region: us-east-1
    cidrBlock: 10.0.0.0/16
    tags:
      Name: staging-vpc2